server:
  port: 3001
  
spring:
  application:
    name: ruul
    
  rabbitmq:
    host: 192.168.161.130
    port: 5672
    username: admin
    password: admin
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**

zuul:
  retryable: true
